"""§9 step 2: ORM models match migration 0001 exactly; schemas never leak
session_players.starting_xp (spec §3.1)."""
import uuid
from datetime import datetime, timezone

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from pydantic import BaseModel, ValidationError

import app.schemas as schemas
from app.models import SessionPlayer
from app.schemas.sessions import SessionPlayerRead, SessionRead
from tests.conftest import alembic_config


def test_models_match_migration(migrated_db: str):
    """`alembic check` against the migrated scratch DB: no autogenerate diff.
    env.py enables type, server-default and CHECK-by-name comparison."""
    try:
        command.check(alembic_config())
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"models diverge from 0001_initial_schema:\n{exc}")


def _all_schema_classes() -> list[type[BaseModel]]:
    return [
        obj
        for obj in vars(schemas).values()
        if isinstance(obj, type) and issubclass(obj, BaseModel)
    ]


def test_no_schema_exposes_starting_xp():
    offenders = [
        cls.__name__ for cls in _all_schema_classes() if "starting_xp" in cls.model_fields
    ]
    assert offenders == []


def test_session_player_serializer_drops_starting_xp():
    """Serializing the ORM row must not carry the secret, and a dict that
    tries to smuggle it in is rejected outright."""
    now = datetime.now(timezone.utc)
    row = SessionPlayer(
        session_id=uuid.uuid4(),
        user_id=uuid.uuid4(),
        display_name="p1",
        starting_xp=18,
        final_xp=None,
        delta_xp=None,
        joined_at=now,
    )
    out = SessionPlayerRead.model_validate(row).model_dump()
    assert "starting_xp" not in out
    assert out["display_name"] == "p1"

    with pytest.raises(ValidationError):
        SessionPlayerRead.model_validate({**out, "starting_xp": 18})

    # Nested through the session read model as well.
    assert "starting_xp" not in SessionRead.model_json_schema()["$defs"]["SessionPlayerRead"][
        "properties"
    ]
    # The session's rng seed would let a client predict the board, the
    # auto-picks and everyone's starting XP: same treatment.
    assert "rng_seed" not in SessionRead.model_json_schema()["properties"]
    assert SessionRead.model_config["extra"] == "forbid"
