"""initial schema (SPEC-phase1 §3)

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-21

The DDL below is the spec's §3 verbatim. It is intentionally raw SQL rather
than autogenerated: partial indexes, CHECK constraints and the pgcrypto/citext
extensions are the invariants the rest of the system relies on, and they must
match the spec exactly.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


UPGRADE_SQL = """
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "citext";

-- ---------- users & billing ----------

CREATE TABLE users (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email           CITEXT UNIQUE,
  display_name    TEXT NOT NULL,
  locale          TEXT NOT NULL DEFAULT 'en' CHECK (locale IN ('en','es')),
  region          TEXT NOT NULL DEFAULT 'global' CHECK (region IN ('us','latam','global')),
  auth_provider   TEXT,
  auth_subject    TEXT,
  role            TEXT NOT NULL DEFAULT 'player' CHECK (role IN ('player','admin')),
  age_gate_passed BOOLEAN NOT NULL DEFAULT FALSE,   -- 13+ attestation, see §7
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (auth_provider, auth_subject)
);

CREATE TABLE subscriptions (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                 UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  platform                TEXT NOT NULL CHECK (platform IN ('ios','android','promo')),
  product_id              TEXT NOT NULL,
  original_transaction_id TEXT UNIQUE,
  status                  TEXT NOT NULL CHECK (status IN ('active','grace','expired','refunded')),
  current_period_end      TIMESTAMPTZ,
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ON subscriptions (user_id, status);

-- ---------- study packs ----------

CREATE TABLE study_packs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title           TEXT NOT NULL,
  source_filename TEXT,
  page_count      INT,
  locale          TEXT NOT NULL CHECK (locale IN ('en','es')),
  status          TEXT NOT NULL DEFAULT 'uploading'
                  CHECK (status IN ('uploading','processing','ready','failed')),
  question_count  INT NOT NULL DEFAULT 0,
  share_code      TEXT UNIQUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ON study_packs (owner_id, created_at DESC);

-- Auditable ticket balance. Never a bare counter: a failed generation
-- must be refundable, and support needs to see why a balance is what it is.
CREATE TABLE ticket_ledger (
  id           BIGSERIAL PRIMARY KEY,
  user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  delta        INT NOT NULL,                  -- +5 monthly grant, -1 spend, +1 refund
  reason       TEXT NOT NULL,                 -- 'monthly_grant','pack_generate','refund_failed','promo'
  pack_id      UUID REFERENCES study_packs(id) ON DELETE SET NULL,
  period_start DATE,                          -- for monthly grants; one grant per period
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ON ticket_ledger (user_id, created_at DESC);
CREATE UNIQUE INDEX ON ticket_ledger (user_id, period_start) WHERE reason = 'monthly_grant';

-- ---------- categories ----------

CREATE TABLE categories (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug       TEXT UNIQUE NOT NULL,            -- 'math','bible','cars','world-history'
  icon       TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE category_translations (
  category_id UUID NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  locale      TEXT NOT NULL CHECK (locale IN ('en','es')),
  name        TEXT NOT NULL,
  description TEXT,
  PRIMARY KEY (category_id, locale)
);

-- ---------- generation jobs ----------

CREATE TABLE generation_jobs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  kind            TEXT NOT NULL CHECK (kind IN ('category','study_pack')),
  requested_by    UUID REFERENCES users(id),
  prompt          TEXT,                        -- the admin's natural-language request
  params          JSONB NOT NULL,              -- see §5.1
  status          TEXT NOT NULL DEFAULT 'queued'
                  CHECK (status IN ('queued','running','succeeded','partial','failed')),
  model           TEXT,
  requested_count INT,
  produced_count  INT NOT NULL DEFAULT 0,      -- returned by model
  accepted_count  INT NOT NULL DEFAULT 0,      -- survived validation, written as pending
  rejected_count  INT NOT NULL DEFAULT 0,      -- failed validation or deduped
  cost_cents      INT,
  error           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at      TIMESTAMPTZ,
  finished_at     TIMESTAMPTZ
);
CREATE INDEX ON generation_jobs (status, created_at DESC);

-- ---------- questions ----------

CREATE TABLE questions (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id       UUID NOT NULL REFERENCES categories(id),
  difficulty        SMALLINT NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
  grade_band        TEXT CHECK (grade_band IN ('g1_g3','g4_g6','g7_g9','g10_g12','adult')),
  region            TEXT NOT NULL DEFAULT 'global' CHECK (region IN ('us','latam','global')),
  tags              TEXT[] NOT NULL DEFAULT '{}',
  correct_index     SMALLINT NOT NULL CHECK (correct_index BETWEEN 0 AND 3),
  status            TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','live','archived','rejected')),
  source            TEXT NOT NULL DEFAULT 'ai'
                    CHECK (source IN ('seed','ai','user','manual')),
  pack_id           UUID REFERENCES study_packs(id) ON DELETE CASCADE,  -- NULL = house content
  generation_job_id UUID REFERENCES generation_jobs(id) ON DELETE SET NULL,
  content_hash      TEXT NOT NULL,             -- sha256 of normalized en stem; dedupe
  reviewed_by       UUID REFERENCES users(id),
  reviewed_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- House content must be unique. Pack content may legitimately repeat
-- across users' uploads, so the constraint is partial.
CREATE UNIQUE INDEX questions_house_hash_uniq
  ON questions (content_hash) WHERE pack_id IS NULL;

-- The hot path: drawing a house question set.
CREATE INDEX questions_house_draw
  ON questions (category_id, difficulty, region)
  WHERE status = 'live' AND pack_id IS NULL;

CREATE INDEX questions_review_queue
  ON questions (status, created_at DESC) WHERE pack_id IS NULL;

CREATE INDEX ON questions (pack_id) WHERE pack_id IS NOT NULL;

CREATE TABLE question_translations (
  question_id UUID NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  locale      TEXT NOT NULL CHECK (locale IN ('en','es')),
  stem        TEXT NOT NULL,
  options     JSONB NOT NULL CHECK (jsonb_array_length(options) = 4),
  explanation TEXT,
  PRIMARY KEY (question_id, locale)
);

-- ---------- telemetry ----------

-- One row per question shown to one player. High volume: ~15 rows per
-- player per session. Partition by month once this passes ~50M rows.
CREATE TABLE question_serves (
  id          BIGSERIAL PRIMARY KEY,
  question_id UUID NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  session_id  UUID NOT NULL,
  user_id     UUID REFERENCES users(id) ON DELETE SET NULL,
  locale      TEXT NOT NULL,
  outcome     TEXT NOT NULL CHECK (outcome IN ('correct','incorrect','timeout','absent')),
  response_ms INT,
  served_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ON question_serves (question_id, served_at DESC);
CREATE INDEX ON question_serves (session_id);

-- Rollup so the admin dashboard never aggregates the raw table.
CREATE TABLE question_stats (
  question_id     UUID PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
  serves          INT NOT NULL DEFAULT 0,
  correct         INT NOT NULL DEFAULT 0,
  incorrect       INT NOT NULL DEFAULT 0,
  timeouts        INT NOT NULL DEFAULT 0,
  reports         INT NOT NULL DEFAULT 0,
  avg_response_ms INT,
  last_served_at  TIMESTAMPTZ
);

CREATE TABLE question_reports (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id UUID NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  user_id     UUID REFERENCES users(id) ON DELETE SET NULL,
  session_id  UUID,
  reason      TEXT NOT NULL CHECK (reason IN ('wrong_answer','typo','offensive','confusing','other')),
  note        TEXT,
  resolved    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ON question_reports (question_id) WHERE resolved = FALSE;

-- ---------- sessions (tables now, engine in Phase 2) ----------

CREATE TABLE sessions (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  host_id        UUID REFERENCES users(id) ON DELETE SET NULL,
  join_code      TEXT UNIQUE NOT NULL,
  locale         TEXT NOT NULL CHECK (locale IN ('en','es')),
  region         TEXT NOT NULL DEFAULT 'global',
  mode           TEXT NOT NULL CHECK (mode IN ('house','study')),
  pack_id        UUID REFERENCES study_packs(id) ON DELETE SET NULL,
  category_ids   UUID[] NOT NULL DEFAULT '{}',
  question_count INT NOT NULL DEFAULT 15,
  status         TEXT NOT NULL DEFAULT 'lobby'
                 CHECK (status IN ('lobby','running','finished','abandoned')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at     TIMESTAMPTZ,
  ended_at       TIMESTAMPTZ
);

CREATE TABLE session_players (
  session_id    UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  display_name  TEXT NOT NULL,
  starting_xp   SMALLINT NOT NULL,             -- 10 | 18 | 30, secret until reveal
  final_xp      SMALLINT,
  delta_xp      SMALLINT,
  joined_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (session_id, user_id)
);

-- Question set is drawn once at session start, never mid-round.
CREATE TABLE session_questions (
  session_id  UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  ordinal     SMALLINT NOT NULL,
  question_id UUID NOT NULL REFERENCES questions(id),
  PRIMARY KEY (session_id, ordinal)
);
"""

# Reverse dependency order: children before parents.
DOWNGRADE_SQL = """
DROP TABLE IF EXISTS session_questions;
DROP TABLE IF EXISTS session_players;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS question_reports;
DROP TABLE IF EXISTS question_stats;
DROP TABLE IF EXISTS question_serves;
DROP TABLE IF EXISTS question_translations;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS generation_jobs;
DROP TABLE IF EXISTS category_translations;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS ticket_ledger;
DROP TABLE IF EXISTS study_packs;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS users;
"""


def _execute_script(sql: str) -> None:
    # psycopg can't take multiple statements in one prepared call, so split
    # on ';' at line end. No statement in this file contains a literal ';'.
    for statement in sql.split(";\n"):
        statement = statement.strip()
        if statement:
            op.execute(statement)


def upgrade() -> None:
    _execute_script(UPGRADE_SQL)


def downgrade() -> None:
    _execute_script(DOWNGRADE_SQL)
